import { MikroTikConfig, RosVersion, WanInterface } from '../types';

export const DEFAULT_CONFIG_FALLBACK: MikroTikConfig = {
  routerName: 'MikroTik-Router',
  rosVersion: 'v7',
  safeMode: true,
  backupBeforeApply: true,
  multiWanMode: 'failover',
  wans: [
    { id: 'w1', name: 'ether1', comment: 'ISP-Indihome', type: 'dhcp', ipAddress: '', gateway: '192.168.1.1', weight: 1, distance: 1, checkGateway: true }
  ],
  lans: [
    { id: 'l1', name: 'bridge-lan', ipAddress: '192.168.88.1/24', dhcpEnabled: true, dhcpPoolStart: '192.168.88.10', dhcpPoolEnd: '192.168.88.250', leaseTime: '12h' }
  ],
  dnsServers: ['1.1.1.1', '8.8.8.8'],
  dnsAllowRemote: true,
  enableFasttrack: true,
  protectRouter: true,
  dropInvalid: true,
  blockDdosRaw: false,
  portForwards: [],
  vlans: [],
  hotspot: {
    enabled: false,
    interface: 'ether2-LAN',
    ipAddress: '10.10.10.1',
    poolName: 'pool_hotspot',
    dnsName: 'wifi.login',
    profileName: 'hsprof1',
    userRateLimit: '2M/5M',
    trialEnabled: true
  },
  pppoe: {
    enabled: false,
    serviceName: 'pppoe-service',
    interface: 'ether3-LAN',
    localAddress: '10.0.0.1',
    remotePool: 'pppoe-pool',
    defaultProfile: 'pppoe-profile'
  },
  queue: {
    type: 'pcq',
    targetNetwork: '192.168.88.0/24',
    maxUpload: '50M',
    maxDownload: '100M',
    pcqRateUpload: '5M',
    pcqRateDownload: '10M',
    qosTrafficSplit: true,
    qosMode: 'simple_queue',
    gameUpload: '10M',
    gameDownload: '20M',
    streamingUpload: '15M',
    streamingDownload: '30M',
    browsingUpload: '10M',
    browsingDownload: '20M',
    heavyUpload: '5M',
    heavyDownload: '10M'
  },
  siteBlocker: {
    enabled: true,
    blockJudol: true,
    blockPorn: true,
    blockTorrent: true,
    blockSosmed: false,
    blockStreaming: false,
    customDomains: ['domain-judi-ilegal.com', 'situs-terlarang.net'],
    blockMethod: 'filter_tls'
  },
  vpn: {
    type: 'none',
    wireguardPort: 13231,
    wireguardAddress: '10.50.0.1/24',
    l2tpSecret: 'MikroTik123!',
    l2tpPool: '10.50.1.0/24'
  },
  tools: {
    cloudDdns: true,
    ntpClient: true,
    ntpServer: 'id.pool.ntp.org',
    autoBackup: true,
    backupTime: '03:00:00',
    netwatchHost: '8.8.8.8',
    netwatchInterval: '30s'
  }
};

export function normalizeConfig(incoming: Partial<MikroTikConfig> | undefined | null, base: MikroTikConfig = DEFAULT_CONFIG_FALLBACK): MikroTikConfig {
  if (!incoming) return base;
  return {
    ...base,
    ...incoming,
    wans: incoming.wans && incoming.wans.length > 0 ? incoming.wans : base.wans,
    lans: incoming.lans && incoming.lans.length > 0 ? incoming.lans : base.lans,
    dnsServers: incoming.dnsServers && incoming.dnsServers.length > 0 ? incoming.dnsServers : base.dnsServers,
    portForwards: incoming.portForwards ?? base.portForwards ?? [],
    vlans: incoming.vlans ?? base.vlans ?? [],
    hotspot: {
      ...base.hotspot!,
      ...(incoming.hotspot || {})
    },
    pppoe: {
      ...base.pppoe!,
      ...(incoming.pppoe || {})
    },
    queue: {
      ...base.queue!,
      ...(incoming.queue || {})
    },
    siteBlocker: {
      ...base.siteBlocker!,
      ...(incoming.siteBlocker || {})
    },
    vpn: {
      ...base.vpn!,
      ...(incoming.vpn || {})
    },
    tools: {
      ...base.tools!,
      ...(incoming.tools || {})
    }
  };
}

export function generateRouterOsScript(rawConfig: MikroTikConfig): string {
  const config = normalizeConfig(rawConfig);
  const v = config.rosVersion;
  const isV7 = v === 'v7';
  const lines: string[] = [];

  const addHeader = (title: string) => {
    lines.push('');
    lines.push('# ==============================================================================');
    lines.push('# ' + title);
    lines.push('# ==============================================================================');
  };

  const addComment = (comment: string) => {
    lines.push('# ' + comment);
  };

  // Header
  lines.push('# ******************************************************************************');
  lines.push('# MIKROTIK ROUTEROS ' + (isV7 ? 'v7' : 'v6') + ' CONFIGURATION SCRIPT');
  lines.push('# Generated by: MIKROTIK CONFIG BUILDER PRO');
  lines.push('# Router Identity : ' + (config.routerName || 'MikroTik-Router'));
  lines.push('# Target ROS Ver  : ' + (isV7 ? 'RouterOS v7.x' : 'RouterOS v6.x'));
  lines.push('# Multi-WAN Mode  : ' + config.multiWanMode.toUpperCase());
  lines.push('# Date Generated  : ' + new Date().toISOString().replace('T', ' ').substring(0, 19));
  lines.push('# ******************************************************************************');

  // Safety & Backup
  if (config.backupBeforeApply) {
    addHeader('SYSTEM SAFETY: BACKUP EXISTING CONFIGURATION');
    const bkpName = (config.routerName || 'router') + '-bkp-' + Date.now();
    lines.push('/system backup save name="' + bkpName + '"');
    lines.push('/export file="' + bkpName + '"');
    lines.push(':delay 2s;');
    addComment('Backup saved as ' + bkpName + '.backup and ' + bkpName + '.rsc');
  }

  if (config.safeMode) {
    addHeader('SYSTEM SAFETY: SAFE MODE ACTIVATION');
    addComment('Safe Mode ensures settings will revert if admin session disconnects.');
    addComment('NOTE: When executing via Terminal/SSH, you can also press [Ctrl]+[X] for Safe Mode.');
  }

  // 1. Router Identity
  addHeader('1. SYSTEM IDENTITY & TIMEZONE');
  lines.push('/system identity set name="' + (config.routerName || 'MikroTik-Router') + '"');
  lines.push('/system clock set time-zone-name="Asia/Jakarta"');

  // NTP Client
  if (config.tools?.ntpClient) {
    addComment('NTP Client Setup for accurate timekeeping');
    if (isV7) {
      lines.push('/system ntp client set enabled=yes');
      lines.push('/system ntp client servers add address="' + (config.tools?.ntpServer || 'id.pool.ntp.org') + '"');
    } else {
      lines.push('/system ntp client set enabled=yes primary-ntp=162.159.200.1 secondary-ntp=129.6.15.28');
    }
  }

  // 2. Interface Lists
  addHeader('2. INTERFACE LISTS (WAN / LAN)');
  lines.push('/interface list');
  lines.push('add name=WAN comment="All WAN Interfaces"');
  lines.push('add name=LAN comment="All Local LAN Interfaces"');

  // 3. Physical Interfaces & Naming
  addHeader('3. INTERFACE NAMING & MEMBERSHIP');
  lines.push('/interface list member');
  config.wans.forEach(wan => {
    lines.push('add list=WAN interface=' + wan.name + ' comment="' + (wan.comment || wan.name) + '"');
  });
  config.lans.forEach(lan => {
    lines.push('add list=LAN interface=' + lan.name);
  });

  // 4. IP Addresses
  addHeader('4. IP ADDRESS CONFIGURATION');
  config.wans.forEach(wan => {
    if (wan.type === 'static' && wan.ipAddress) {
      lines.push('/ip address add address=' + wan.ipAddress + ' interface=' + wan.name + ' comment="IP-WAN-' + wan.name + '"');
    } else if (wan.type === 'dhcp') {
      lines.push('/ip dhcp-client add interface=' + wan.name + ' disabled=no use-peer-dns=yes use-peer-ntp=yes add-default-route=' + (config.wans.length > 1 ? 'no' : 'yes') + ' comment="DHCP-CLIENT-' + wan.name + '"');
    }
  });

  config.lans.forEach(lan => {
    if (lan.ipAddress) {
      lines.push('/ip address add address=' + lan.ipAddress + ' interface=' + lan.name + ' comment="IP-LAN-' + lan.name + '"');
    }
  });

  // 5. IP Pools & DHCP Server for LAN
  const activeDhcpLans = config.lans.filter(l => l.dhcpEnabled);
  if (activeDhcpLans.length > 0) {
    addHeader('5. DHCP POOL & DHCP SERVER');
    activeDhcpLans.forEach(lan => {
      const poolName = 'pool_' + lan.name;
      const serverName = 'dhcp_' + lan.name;
      const gw = lan.ipAddress.split('/')[0];
      const subnetParts = lan.ipAddress.split('/');
      const netBase = subnetParts[0].split('.').slice(0, 3).join('.') + '.0/' + (subnetParts[1] || '24');

      lines.push('/ip pool add name=' + poolName + ' ranges=' + lan.dhcpPoolStart + '-' + lan.dhcpPoolEnd);
      lines.push('/ip dhcp-server add name=' + serverName + ' interface=' + lan.name + ' address-pool=' + poolName + ' lease-time=' + (lan.leaseTime || '12h') + ' disabled=no');
      lines.push('/ip dhcp-server network add address=' + netBase + ' gateway=' + gw + ' dns-server=' + (config.dnsServers.join(',') || '8.8.8.8,1.1.1.1') + ' comment="DHCP-Network-' + lan.name + '"');
    });
  }

  // 6. DNS Setup
  addHeader('6. DNS CACHE & RESOLVER');
  lines.push('/ip dns set allow-remote-requests=' + (config.dnsAllowRemote ? 'yes' : 'no') + ' servers=' + config.dnsServers.join(',') + ' cache-size=4096KiB');

  // 7. VLAN Setup (if any)
  if (config.vlans.length > 0) {
    addHeader('7. VLAN CONFIGURATION (BRIDGE VLAN FILTERING)');
    lines.push('/interface bridge');
    lines.push('add name=bridge-vlan vlan-filtering=no comment="Bridge for VLAN Trunking"');

    config.vlans.forEach(vlan => {
      lines.push('/interface vlan add name=' + vlan.name + ' vlan-id=' + vlan.vlanId + ' interface=' + (vlan.bridge || 'bridge-vlan'));
      if (vlan.ipAddress) {
        lines.push('/ip address add address=' + vlan.ipAddress + ' interface=' + vlan.name + ' comment="IP-VLAN-' + vlan.vlanId + '"');
      }
      if (vlan.dhcpEnabled) {
        const vlanPool = 'pool_' + vlan.name;
        const parts = vlan.ipAddress.split('/');
        const gw = parts[0];
        const base = parts[0].split('.').slice(0, 3).join('.');
        lines.push('/ip pool add name=' + vlanPool + ' ranges=' + base + '.10-' + base + '.250');
        lines.push('/ip dhcp-server add name=dhcp_' + vlan.name + ' interface=' + vlan.name + ' address-pool=' + vlanPool + ' disabled=no');
        lines.push('/ip dhcp-server network add address=' + base + '.0/' + (parts[1] || '24') + ' gateway=' + gw + ' dns-server=' + config.dnsServers.join(','));
      }
    });

    lines.push('/interface bridge vlan');
    config.vlans.forEach(vlan => {
      const tagged = vlan.taggedPorts.length > 0 ? ' tagged=' + vlan.taggedPorts.join(',') : '';
      const untagged = vlan.untaggedPorts.length > 0 ? ' untagged=' + vlan.untaggedPorts.join(',') : '';
      lines.push('add bridge=' + (vlan.bridge || 'bridge-vlan') + ' vlan-ids=' + vlan.vlanId + tagged + untagged);
    });

    addComment('Enable vlan-filtering once ports are assigned');
    lines.push('/interface bridge set bridge-vlan vlan-filtering=yes');
  }

  // 8. Multi-WAN & Routing
  if (config.wans.length === 1) {
    addHeader('8. ROUTING: SINGLE WAN DEFAULT ROUTE');
    const wan = config.wans[0];
    if (wan.type === 'static' && wan.gateway) {
      lines.push('/ip route add dst-address=0.0.0.0/0 gateway=' + wan.gateway + ' check-gateway=ping distance=1 comment="Default-Route-WAN1"');
    }
  } else if (config.wans.length > 1) {
    if (config.multiWanMode === 'ecmp') {
      addHeader('8. MULTI-WAN: EQUAL COST MULTI-PATH (ECMP)');
      const gateways = config.wans.map(w => w.gateway).filter(Boolean).join(',');
      lines.push('/ip route add dst-address=0.0.0.0/0 gateway=' + gateways + ' check-gateway=ping comment="ECMP-Multi-WAN-Route"');
    } else if (config.multiWanMode === 'failover') {
      addHeader('8. MULTI-WAN: FAILOVER WITH DISTANCE & CHECK GATEWAY');
      config.wans.forEach((w, idx) => {
        const dist = w.distance || (idx + 1);
        lines.push('/ip route add dst-address=0.0.0.0/0 gateway=' + w.gateway + ' distance=' + dist + ' check-gateway=ping comment="Failover-' + w.name + '-Dist-' + dist + '"');
      });
    } else if (config.multiWanMode === 'recursive') {
      addHeader('8. MULTI-WAN: RECURSIVE ROUTING (DNS HOST CANARY)');
      const canaries = ['8.8.8.8', '1.1.1.1', '9.9.9.9', '208.67.222.222'];
      config.wans.forEach((w, idx) => {
        const canary = canaries[idx] || ('8.8.4.' + (idx + 1));
        const dist = idx + 1;
        addComment('WAN ' + (idx + 1) + ' Routes to Canary ' + canary);
        lines.push('/ip route add dst-address=' + canary + ' gateway=' + w.gateway + ' scope=10 comment="Host-Route-' + w.name + '"');
        lines.push('/ip route add dst-address=0.0.0.0/0 gateway=' + canary + ' check-gateway=ping distance=' + dist + ' target-scope=30 comment="Recursive-Default-' + w.name + '"');
      });
    } else {
      // PCC Equal or Weighted
      const isWeighted = config.multiWanMode === 'pcc_weighted';
      addHeader('8. MULTI-WAN: PCC LOAD BALANCING (' + (isWeighted ? 'WEIGHTED' : 'EQUAL') + ')');

      // Local RFC1918 address list to exclude local-to-local traffic from mangle
      lines.push('/ip firewall address-list');
      lines.push('add address=10.0.0.0/8 list=RFC1918-LOCAL comment="Private Class A"');
      lines.push('add address=172.16.0.0/12 list=RFC1918-LOCAL comment="Private Class B"');
      lines.push('add address=192.168.0.0/16 list=RFC1918-LOCAL comment="Private Class C"');

      // RouterOS v7 Routing Table Definition
      if (isV7) {
        lines.push('');
        addComment('RouterOS v7 requires creating routing tables first:');
        lines.push('/routing table');
        config.wans.forEach(w => {
          lines.push('add name=to_' + w.name + ' fib comment="Routing table for ' + w.name + '"');
        });
      }

      // Mangle Rules
      lines.push('');
      lines.push('/ip firewall mangle');
      addComment('Bypass local traffic from mangle');
      lines.push('add chain=prerouting dst-address-list=RFC1918-LOCAL action=accept comment="BYPASS LOCAL SUBNETS"');

      // Mark Connection from outside into each WAN
      addComment('Mark incoming connections from WAN interfaces so replies go out the same WAN');
      config.wans.forEach(w => {
        lines.push('add chain=prerouting in-interface=' + w.name + ' connection-mark=no-mark action=mark-connection new-connection-mark=' + w.name + '_conn passthrough=yes comment="IN-' + w.name + '-CONN"');
      });

      // PCC Mangle Classifiers
      addComment('PCC (Per Connection Classifier) distribution rules:');
      if (!isWeighted) {
        const totalWans = config.wans.length;
        config.wans.forEach((w, idx) => {
          lines.push('add chain=prerouting in-interface-list=LAN connection-mark=no-mark dst-address-type=!local dst-address-list=!RFC1918-LOCAL per-connection-classifier=both-addresses-and-ports:' + totalWans + '/' + idx + ' action=mark-connection new-connection-mark=' + w.name + '_conn passthrough=yes comment="PCC-' + totalWans + '-' + idx + '-' + w.name + '"');
        });
      } else {
        // Weighted PCC
        const totalWeight = config.wans.reduce((sum, w) => sum + (w.weight || 1), 0);
        let currentSlot = 0;
        config.wans.forEach(w => {
          const count = w.weight || 1;
          for (let i = 0; i < count; i++) {
            lines.push('add chain=prerouting in-interface-list=LAN connection-mark=no-mark dst-address-type=!local dst-address-list=!RFC1918-LOCAL per-connection-classifier=both-addresses-and-ports:' + totalWeight + '/' + currentSlot + ' action=mark-connection new-connection-mark=' + w.name + '_conn passthrough=yes comment="PCC-WEIGHT-' + w.name + '-' + totalWeight + '-' + currentSlot + '"');
            currentSlot++;
          }
        });
      }

      // Mark Routing for LAN
      addComment('Assign routing mark based on connection mark');
      config.wans.forEach(w => {
        lines.push('add chain=prerouting connection-mark=' + w.name + '_conn in-interface-list=LAN action=mark-routing new-routing-mark=to_' + w.name + ' passthrough=yes comment="ROUTE-MARK-' + w.name + '"');
      });

      // Output chain for router own traffic
      addComment('Ensure router-originated traffic follows connection marks');
      config.wans.forEach(w => {
        lines.push('add chain=output connection-mark=' + w.name + '_conn action=mark-routing new-routing-mark=to_' + w.name + ' passthrough=no comment="OUTPUT-ROUTE-' + w.name + '"');
      });

      // Routes for each routing table
      lines.push('');
      addHeader('ROUTING TABLES & DEFAULT ROUTES');
      config.wans.forEach(w => {
        if (isV7) {
          lines.push('/ip route add dst-address=0.0.0.0/0 gateway=' + w.gateway + ' routing-table=to_' + w.name + ' check-gateway=ping distance=1 comment="Route-' + w.name + '"');
        } else {
          lines.push('/ip route add dst-address=0.0.0.0/0 gateway=' + w.gateway + ' routing-mark=to_' + w.name + ' check-gateway=ping distance=1 comment="Route-' + w.name + '"');
        }
      });

      // Main default routing with failover distance
      addComment('Main routing table default routes (with failover distance):');
      config.wans.forEach((w, idx) => {
        const dist = idx + 1;
        lines.push('/ip route add dst-address=0.0.0.0/0 gateway=' + w.gateway + ' check-gateway=ping distance=' + dist + ' comment="Main-Default-WAN' + dist + '"');
      });
    }
  }

  // 9. NAT (Masquerade & Port Forwarding)
  addHeader('9. NAT (MASQUERADE & PORT FORWARDING)');
  lines.push('/ip firewall nat');
  config.wans.forEach(w => {
    lines.push('add chain=srcnat out-interface=' + w.name + ' action=masquerade comment="MASQUERADE-' + w.name + '"');
  });

  if (config.portForwards.length > 0) {
    addComment('Port Forwarding (dst-nat) rules:');
    config.portForwards.forEach(pf => {
      const inInt = pf.inInterface ? ' in-interface=' + pf.inInterface : ' in-interface-list=WAN';
      lines.push('add chain=dstnat' + inInt + ' protocol=' + pf.protocol + ' dst-port=' + pf.dstPort + ' action=dst-nat to-addresses=' + pf.toAddress + ' to-ports=' + pf.toPort + ' comment="' + (pf.comment || 'PORT-FWD-' + pf.dstPort) + '"');
    });
  }

  // 9.5 MANGLE RULES FOR QOS TRAFFIC SEPARATION (GAME, STREAMING, BROWSING, DOWNLOAD)
  if (config.queue.qosTrafficSplit) {
    addHeader('MANGLE RULES: QOS TRAFFIC SEPARATION (GAME, STREAMING, BROWSING, HEAVY)');
    lines.push('/ip firewall mangle');

    addComment('QoS Priority 1: Game Online (Mobile Legends, PUBG, Free Fire, Valorant, Dota 2, Roblox, Genshin)');
    lines.push('add chain=prerouting protocol=udp dst-port=5000-5200,5500-5700,9000-9010,10012,10491,10612,17500,18081,20000-20002,7006,39003,39698,39779,39800,7000-8000,8180-8181,27000-27100,4380,22101-22102 action=mark-connection new-connection-mark=cm_game passthrough=yes comment="QoS: Conn Game UDP"');
    lines.push('add chain=prerouting protocol=tcp dst-port=7889,10012,2099,5222,5223,27015-27030 action=mark-connection new-connection-mark=cm_game passthrough=yes comment="QoS: Conn Game TCP"');
    lines.push('add chain=prerouting connection-mark=cm_game action=mark-packet new-packet-mark=pk_game passthrough=no comment="QoS: Packet Game Online"');

    addComment('QoS Priority 4: Streaming Video/Audio (YouTube, TikTok, Netflix, QUIC, RTMP)');
    lines.push('add chain=prerouting protocol=udp dst-port=443 action=mark-connection new-connection-mark=cm_streaming passthrough=yes comment="QoS: Conn Streaming QUIC UDP"');
    lines.push('add chain=prerouting protocol=tcp dst-port=1935,8080,8081 action=mark-connection new-connection-mark=cm_streaming passthrough=yes comment="QoS: Conn Streaming RTMP/Web"');
    lines.push('add chain=prerouting connection-mark=cm_streaming action=mark-packet new-packet-mark=pk_streaming passthrough=no comment="QoS: Packet Streaming"');

    addComment('QoS Priority 6: Browsing & Social Media (Web surfing under 1MB connection bytes)');
    lines.push('add chain=prerouting protocol=tcp dst-port=80,443 connection-bytes=0-1048576 action=mark-connection new-connection-mark=cm_browsing passthrough=yes comment="QoS: Conn Browsing & Sosmed"');
    lines.push('add chain=prerouting connection-mark=cm_browsing action=mark-packet new-packet-mark=pk_browsing passthrough=no comment="QoS: Packet Browsing"');

    addComment('QoS Priority 8: Heavy Download / Large File Transfers (> 1MB connection bytes)');
    lines.push('add chain=prerouting protocol=tcp dst-port=80,443 connection-bytes=1048577-0 action=mark-connection new-connection-mark=cm_heavy passthrough=yes comment="QoS: Conn Heavy Download"');
    lines.push('add chain=prerouting connection-mark=cm_heavy action=mark-packet new-packet-mark=pk_heavy passthrough=no comment="QoS: Packet Heavy Download"');
  }

  // 10. Firewall Filter & Raw
  addHeader('10. FIREWALL FILTER RULES (SECURITY HARDENING)');
  lines.push('/ip firewall filter');

  // Fasttrack
  if (config.enableFasttrack) {
    if (config.queue.qosTrafficSplit) {
      addComment('NOTICE: QoS active. FastTrack only applied to no-mark packets so queue prioritization works accurately!');
      lines.push('add chain=forward action=fasttrack-connection connection-state=established,related connection-mark=no-mark packet-mark=no-mark comment="FastTrack Non-QoS Only"');
    } else if (config.wans.length > 1 && (config.multiWanMode === 'pcc_equal' || config.multiWanMode === 'pcc_weighted')) {
      addComment('FastTrack conditioned: bypass only non-PCC marked or specific traffic to prevent breaking Load Balance');
      lines.push('add chain=forward action=fasttrack-connection connection-state=established,related connection-mark=no-mark comment="FastTrack Established/Related"');
    } else {
      lines.push('add chain=forward action=fasttrack-connection connection-state=established,related comment="FastTrack Established/Related"');
    }
  }

  // Established, Related, Untracked
  lines.push('add chain=input action=accept connection-state=established,related,untracked comment="Accept Established/Related"');
  lines.push('add chain=forward action=accept connection-state=established,related,untracked comment="Accept Established/Related"');

  // Drop Invalid
  if (config.dropInvalid) {
    lines.push('add chain=input action=drop connection-state=invalid comment="Drop Invalid Input"');
    lines.push('add chain=forward action=drop connection-state=invalid comment="Drop Invalid Forward"');
  }

  // ICMP limit
  lines.push('add chain=input protocol=icmp limit=50/5s,5:packet action=accept comment="Allow ICMP (Ping) with Rate Limit"');

  // Protect Router Input from WAN
  if (config.protectRouter) {
    lines.push('add chain=input in-interface-list=WAN action=drop comment="DEFENSE: Drop All Other WAN Inputs"');
  }

  // SITE BLOCKER / BLOKIR SITUS (JUDI ONLINE, PORNOGRAFI, TORRENT, SOSMED)
  if (config.siteBlocker && config.siteBlocker.enabled) {
    const sb = config.siteBlocker;
    addHeader('SITE BLOCKER: BLOKIR SITUS & KONTEN');

    // Collect keywords
    const blockKeywords: { category: string; keywords: string[] }[] = [];
    if (sb.blockJudol) {
      blockKeywords.push({
        category: 'JUDI ONLINE / SLOT',
        keywords: ['*slot*', '*gacor*', '*judol*', '*togel*', '*sbobet*', '*maxwin*', '*zeus*', '*pragmatic*', '*casino*', '*poker*', '*taruhan*', '*depo*']
      });
    }
    if (sb.blockPorn) {
      blockKeywords.push({
        category: 'KONTEN DEWASA / PORN',
        keywords: ['*porn*', '*xxx*', '*xvideos*', '*xnxx*', '*bokep*', '*onlyfans*', '*redtube*', '*pornhub*']
      });
    }
    if (sb.blockSosmed) {
      blockKeywords.push({
        category: 'MEDIA SOSIAL',
        keywords: ['*tiktok*', '*facebook*', '*instagram*', '*twitter*', '*x.com*']
      });
    }
    if (sb.blockStreaming) {
      blockKeywords.push({
        category: 'STREAMING VIDEO',
        keywords: ['*netflix*', '*youtube*', '*disneyplus*']
      });
    }
    if (sb.customDomains && sb.customDomains.length > 0) {
      blockKeywords.push({
        category: 'CUSTOM DOMAINS',
        keywords: sb.customDomains.map(d => d.trim()).filter(Boolean)
      });
    }

    // Torrent blocking via Port filter
    if (sb.blockTorrent) {
      lines.push('/ip firewall filter');
      lines.push('add chain=forward protocol=tcp dst-port=6881-6889,2710,6969 action=drop comment="BLOKIR: BitTorrent / P2P Port TCP"');
      lines.push('add chain=forward protocol=udp dst-port=6881-6889,2710,6969 action=drop comment="BLOKIR: BitTorrent / P2P Port UDP"');
    }

    // Block method implementation
    if (sb.blockMethod === 'filter_tls') {
      lines.push('/ip firewall filter');
      blockKeywords.forEach(item => {
        item.keywords.forEach(kw => {
          lines.push('add chain=forward protocol=tcp dst-port=443 tls-host="' + kw + '" action=drop comment="BLOKIR TLS: ' + item.category + '"');
        });
      });
    } else if (sb.blockMethod === 'raw_drop') {
      addComment('High-performance RAW PreRouting Drop via Address List');
      lines.push('/ip firewall address-list');
      blockKeywords.forEach(item => {
        item.keywords.forEach(kw => {
          const cleanHost = kw.replace(/[*]/g, '');
          lines.push('add address=' + cleanHost + ' list=BLOCKED_SITES comment="' + item.category + '"');
        });
      });
      lines.push('/ip firewall raw');
      lines.push('add chain=prerouting dst-address-list=BLOCKED_SITES action=drop comment="BLOKIR RAW: Drop Blocked Sites"');
    } else if (sb.blockMethod === 'dns_redirect') {
      addComment('DNS Sinkhole Redirection (Redirect to 127.0.0.1)');
      lines.push('/ip dns static');
      blockKeywords.forEach(item => {
        item.keywords.forEach(kw => {
          lines.push('add name="' + kw + '" address=127.0.0.1 comment="SINKHOLE: ' + item.category + '"');
        });
      });
    }
  }

  // RAW DDoS / Anti Port Scan
  if (config.blockDdosRaw) {
    addHeader('RAW FIREWALL: DDOS & PORT SCAN MITIGATION');
    lines.push('/ip firewall raw');
    lines.push('add chain=prerouting protocol=tcp tcp-flags=fin,syn,rst,psh,ack,urg action=drop comment="Drop TCP Xmas Scan"');
    lines.push('add chain=prerouting protocol=tcp tcp-flags=!fin,!syn,!rst,!psh,!ack,!urg action=drop comment="Drop TCP Null Scan"');
    lines.push('add chain=prerouting protocol=tcp tcp-flags=syn,rst action=drop comment="Drop SYN & RST flag scan"');
  }

  // 11. Hotspot Setup
  if (config.hotspot.enabled) {
    addHeader('11. HOTSPOT SERVER & VOUCHER SETUP');
    const hs = config.hotspot;
    lines.push('/ip hotspot profile');
    lines.push('add name=' + (hs.profileName || 'hsprof1') + ' hotspot-address=' + hs.ipAddress + ' dns-name="' + (hs.dnsName || 'wifi.login') + '" login-by=http-chap,cookie,trial trial-uptime=30m/1d');
    lines.push('/ip hotspot');
    lines.push('add name=hotspot1 interface=' + (hs.interface || 'ether2') + ' profile=' + (hs.profileName || 'hsprof1') + ' address-pool=' + (hs.poolName || 'pool_hotspot') + ' disabled=no');
    lines.push('/ip hotspot user profile');
    lines.push('add name=uprof_standard rate-limit="' + (hs.userRateLimit || '2M/5M') + '" shared-users=1');
    lines.push('/ip hotspot walled-garden');
    lines.push('add dst-host=*.mikrotik.com comment="MikroTik website"');
    lines.push('add dst-host=*.google.com comment="Google"');
  }

  // 12. PPPoE Server Setup
  if (config.pppoe.enabled) {
    addHeader('12. PPPOE SERVER');
    const pp = config.pppoe;
    lines.push('/interface pppoe-server server');
    lines.push('add service-name=' + (pp.serviceName || 'pppoe-srv') + ' interface=' + (pp.interface || 'ether2') + ' default-profile=' + (pp.defaultProfile || 'default') + ' disabled=no');
    lines.push('/ppp profile');
    lines.push('add name=prof-pppoe local-address=' + (pp.localAddress || '172.16.1.1') + ' remote-address=' + (pp.remotePool || 'pool_lan') + ' dns-server=' + config.dnsServers.join(','));
  }

  // 13. Queue & Bandwidth Management
  if (config.queue.qosTrafficSplit) {
    // Advanced QoS Mode (Game, Streaming, Browsing, Heavy)
    if (config.queue.qosMode === 'simple_queue') {
      addHeader('13. BANDWIDTH MANAGEMENT: HIERARCHICAL SIMPLE QUEUE (GAME, STREAMING, BROWSING, HEAVY)');
      lines.push('/queue simple');
      const targetNet = config.queue.targetNetwork || '192.168.88.0/24';
      lines.push('add name="00_TOTAL_BANDWIDTH_PARENT" target="' + targetNet + '" max-limit=' + config.queue.maxUpload + '/' + config.queue.maxDownload + ' priority=8/8 comment="Parent Bandwidth Target"');
      lines.push('add name="01_GAME_ONLINE" parent="00_TOTAL_BANDWIDTH_PARENT" packet-marks=pk_game priority=1/1 limit-at=' + (config.queue.gameUpload || '5M') + '/' + (config.queue.gameDownload || '10M') + ' max-limit=' + (config.queue.gameUpload || '10M') + '/' + (config.queue.gameDownload || '20M') + ' queue=default/default comment="QoS Priority 1: Game Online Low Latency"');
      lines.push('add name="02_STREAMING_VIDEO" parent="00_TOTAL_BANDWIDTH_PARENT" packet-marks=pk_streaming priority=4/4 limit-at=' + (config.queue.streamingUpload || '5M') + '/' + (config.queue.streamingDownload || '15M') + ' max-limit=' + (config.queue.streamingUpload || '15M') + '/' + (config.queue.streamingDownload || '30M') + ' queue=default/default comment="QoS Priority 4: Streaming Video/Audio"');
      lines.push('add name="03_BROWSING_SOSMED" parent="00_TOTAL_BANDWIDTH_PARENT" packet-marks=pk_browsing priority=6/6 limit-at=' + (config.queue.browsingUpload || '5M') + '/' + (config.queue.browsingDownload || '10M') + ' max-limit=' + (config.queue.browsingUpload || '10M') + '/' + (config.queue.browsingDownload || '20M') + ' queue=default/default comment="QoS Priority 6: Web Browsing & Social Media"');
      lines.push('add name="04_HEAVY_DOWNLOAD" parent="00_TOTAL_BANDWIDTH_PARENT" packet-marks=pk_heavy priority=8/8 limit-at=' + (config.queue.heavyUpload || '2M') + '/' + (config.queue.heavyDownload || '5M') + ' max-limit=' + (config.queue.heavyUpload || '5M') + '/' + (config.queue.heavyDownload || '10M') + ' queue=default/default comment="QoS Priority 8: Heavy Downloads & Transfers"');
    } else {
      // Queue Tree HTB Mode
      addHeader('13. BANDWIDTH MANAGEMENT: QUEUE TREE HTB (GAME, STREAMING, BROWSING, HEAVY)');
      lines.push('/queue type');
      lines.push('add name="PCQ_Game_Down" kind=pcq pcq-rate=0 pcq-classifier=dst-address');
      lines.push('add name="PCQ_Game_Up" kind=pcq pcq-rate=0 pcq-classifier=src-address');
      lines.push('add name="PCQ_Stream_Down" kind=pcq pcq-rate=' + (config.queue.streamingDownload || '20M') + ' pcq-classifier=dst-address');
      lines.push('add name="PCQ_Stream_Up" kind=pcq pcq-rate=' + (config.queue.streamingUpload || '5M') + ' pcq-classifier=src-address');
      lines.push('add name="PCQ_Browse_Down" kind=pcq pcq-rate=' + (config.queue.browsingDownload || '10M') + ' pcq-classifier=dst-address');
      lines.push('add name="PCQ_Browse_Up" kind=pcq pcq-rate=' + (config.queue.browsingUpload || '5M') + ' pcq-classifier=src-address');
      lines.push('add name="PCQ_Heavy_Down" kind=pcq pcq-rate=' + (config.queue.heavyDownload || '10M') + ' pcq-classifier=dst-address');
      lines.push('add name="PCQ_Heavy_Up" kind=pcq pcq-rate=' + (config.queue.heavyUpload || '2M') + ' pcq-classifier=src-address');

      lines.push('/queue tree');
      lines.push('add name="ROOT_DOWNLOAD" parent=global max-limit=' + config.queue.maxDownload + ' comment="HTB Root Global Download"');
      lines.push('add name="ROOT_UPLOAD" parent=global max-limit=' + config.queue.maxUpload + ' comment="HTB Root Global Upload"');

      lines.push('add name="01_Game_Down" parent="ROOT_DOWNLOAD" packet-mark=pk_game priority=1 queue=PCQ_Game_Down max-limit=' + (config.queue.gameDownload || '20M') + ' comment="Priority 1: Game Download"');
      lines.push('add name="01_Game_Up" parent="ROOT_UPLOAD" packet-mark=pk_game priority=1 queue=PCQ_Game_Up max-limit=' + (config.queue.gameUpload || '10M') + ' comment="Priority 1: Game Upload"');

      lines.push('add name="02_Stream_Down" parent="ROOT_DOWNLOAD" packet-mark=pk_streaming priority=4 queue=PCQ_Stream_Down max-limit=' + (config.queue.streamingDownload || '30M') + ' comment="Priority 4: Streaming Download"');
      lines.push('add name="02_Stream_Up" parent="ROOT_UPLOAD" packet-mark=pk_streaming priority=4 queue=PCQ_Stream_Up max-limit=' + (config.queue.streamingUpload || '15M') + ' comment="Priority 4: Streaming Upload"');

      lines.push('add name="03_Browse_Down" parent="ROOT_DOWNLOAD" packet-mark=pk_browsing priority=6 queue=PCQ_Browse_Down max-limit=' + (config.queue.browsingDownload || '20M') + ' comment="Priority 6: Browsing Download"');
      lines.push('add name="03_Browse_Up" parent="ROOT_UPLOAD" packet-mark=pk_browsing priority=6 queue=PCQ_Browse_Up max-limit=' + (config.queue.browsingUpload || '10M') + ' comment="Priority 6: Browsing Upload"');

      lines.push('add name="04_Heavy_Down" parent="ROOT_DOWNLOAD" packet-mark=pk_heavy priority=8 queue=PCQ_Heavy_Down max-limit=' + (config.queue.heavyDownload || '10M') + ' comment="Priority 8: Heavy Download"');
      lines.push('add name="04_Heavy_Up" parent="ROOT_UPLOAD" packet-mark=pk_heavy priority=8 queue=PCQ_Heavy_Up max-limit=' + (config.queue.heavyUpload || '5M') + ' comment="Priority 8: Heavy Upload"');
    }
  } else {
    // Standard Non-split Queue
    if (config.queue.type === 'simple') {
      addHeader('13. BANDWIDTH MANAGEMENT: SIMPLE QUEUE');
      lines.push('/queue simple');
      lines.push('add name="Total_Bandwidth_LAN" target="' + (config.queue.targetNetwork || '192.168.88.0/24') + '" max-limit=' + config.queue.maxUpload + '/' + config.queue.maxDownload + ' priority=8/8 comment="Simple Queue for LAN"');
    } else if (config.queue.type === 'pcq') {
      addHeader('13. BANDWIDTH MANAGEMENT: PCQ DYNAMIC EQUAL SHARE');
      lines.push('/queue type');
      lines.push('add name="PCQ_Download" kind=pcq pcq-rate=' + (config.queue.pcqRateDownload || '5M') + ' pcq-classifier=dst-address');
      lines.push('add name="PCQ_Upload" kind=pcq pcq-rate=' + (config.queue.pcqRateUpload || '2M') + ' pcq-classifier=src-address');
      lines.push('/queue simple');
      lines.push('add name="PCQ_LAN_All" target="' + (config.queue.targetNetwork || '192.168.88.0/24') + '" max-limit=' + config.queue.maxUpload + '/' + config.queue.maxDownload + ' queue=PCQ_Upload/PCQ_Download comment="PCQ Equal Dynamic Distribution"');
    } else if (config.queue.type === 'tree') {
      addHeader('13. BANDWIDTH MANAGEMENT: QUEUE TREE');
      lines.push('/queue tree');
      lines.push('add name="Total_Download" parent=global max-limit=' + config.queue.maxDownload + ' comment="Global Download Queue Tree"');
      lines.push('add name="Total_Upload" parent=global max-limit=' + config.queue.maxUpload + ' comment="Global Upload Queue Tree"');
    }
  }

  // 14. VPN Setup
  if (config.vpn.type === 'wireguard' && isV7) {
    addHeader('14. WIREGUARD VPN (ROUTEROS v7)');
    lines.push('/interface wireguard add name=wireguard1 listen-port=' + (config.vpn.wireguardPort || 13231) + ' comment="WireGuard VPN Server"');
    lines.push('/ip address add address=' + (config.vpn.wireguardAddress || '10.50.0.1/24') + ' interface=wireguard1 comment="WireGuard Subnet"');
    lines.push('/ip firewall filter add chain=input protocol=udp dst-port=' + (config.vpn.wireguardPort || 13231) + ' action=accept comment="Allow WireGuard Handshake"');
  } else if (config.vpn.type === 'l2tp') {
    addHeader('14. L2TP / IPSEC VPN SERVER');
    lines.push('/interface l2tp-server server set enabled=yes use-ipsec=yes ipsec-secret="' + (config.vpn.l2tpSecret || 'MikroTikSecret123') + '"');
  }

  // 15. Tools, Netwatch, Scheduler & Cloud DDNS
  addHeader('15. MONITORING, NETWATCH, SCHEDULER & CLOUD DDNS');
  if (config.tools.cloudDdns) {
    lines.push('/ip cloud set ddns-enabled=yes update-time=yes');
    addComment('MikroTik Cloud DNS active. Check with /ip cloud print');
  }

  if (config.tools.netwatchHost) {
    lines.push('/tool netwatch add host=' + config.tools.netwatchHost + ' interval=' + (config.tools.netwatchInterval || '30s') + ' up-script=":log info \\"Netwatch: Host ' + config.tools.netwatchHost + ' UP\\"" down-script=":log error \\"Netwatch: Host ' + config.tools.netwatchHost + ' DOWN!\\"" comment="Canary Ping Check"');
  }

  if (config.tools.autoBackup) {
    lines.push('/system scheduler add name="Daily_Auto_Backup" start-time=' + (config.tools.backupTime || '03:00:00') + ' interval=1d on-event="/system backup save name=\\"auto-daily-backup\\"; /export file=\\"auto-daily-backup\\"; :log info \\"Daily Auto Backup Completed\\"" comment="Daily 3AM Backup"');
  }

  lines.push('');
  lines.push('# ==============================================================================');
  lines.push('# CONFIGURATION SCRIPT COMPLETED SUCCESSFULLY');
  lines.push('# Paste into RouterOS Terminal via Winbox, SSH, or WebFig.');
  lines.push('# ==============================================================================');

  return lines.join('\r\n');
}
